export default interface IUser {
    username: string,
    name: string,
    lastname?: string,
    phone: string,
    email: string,
    idNumber?: string,
    password: string,
    userType: number,
    birthday: Date,
    country?: string,
    province?: string,
    vip?: boolean,
    suscription?: string,
    status?: boolean,
    fcmToken?: string,
    mpPayerId?: number,
    mercadopago_email?: string,
}